services:
  upwork-job-listing-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upwork-job-listing-scraper
    volumes:
      # Mount storage directory for persistent data
      - ./storage:/app/storage
      # Mount logs directory
      - ./logs:/app/logs
      # Mount SQLite data directory for persistent job tracking
      - sqlite_data:/app/sqlite_data
      # Optional: mount source code for development (uncomment for dev mode)
      # - ./src:/app/src
    restart: "no"
    # Resource limits
    mem_limit: 2g
    memswap_limit: 2g
    # Security options
    security_opt:
      - no-new-privileges:true
    # Running as root user (no permission issues)
    environment:
      # Application configuration
      - LOCAL_STORAGE_DIR=/app/storage
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # Proxy configuration (new environment variables)
      - PROXY_URL=${PROXY_URL:-}

      # Database configuration
      - ROCKSDB_DATA_DIR=/app/sqlite_data

  sqlite-viewer:
    image: coleifer/sqlite-web
    container_name: sqlite-viewer
    volumes:
      # Mount the same SQLite data directory to view the database
      - sqlite_data:/data
    ports:
      # Expose SQLite viewer on port 8081
      - "8081:8080"
    command: ["sqlite_web", "/data/jobs.db", "--host", "0.0.0.0", "--port", "8080"]
    restart: unless-stopped
    depends_on:
      - upwork-job-listing-scraper
    # Security options
    security_opt:
      - no-new-privileges:true

# Volumes for persistent data
volumes:
  sqlite_data:
    driver: local

networks:
  default:
    name: upwork-job-listing-scraper-network
