# Compose file for the Firestore-backed Go API.
# Mount a Google service account JSON and export API_KEY before running.
services:
  upwork-job-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: upwork-job-api
    ports:
      - "8080:8080"
    environment:
      - API_KEY=${API_KEY:-your-secret-api-key-here}
      - PORT=8080
      - FIREBASE_SERVICE_ACCOUNT_PATH=/app/config/firebase-service-account.json
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIRESTORE_COLLECTION=${FIRESTORE_COLLECTION:-individual_jobs}
      - FIRESTORE_JOB_LIST_COLLECTION=${FIRESTORE_JOB_LIST_COLLECTION:-job_list}
    volumes:
      - /root/upwork-job-scraper-d1f2c-firebase-adminsdk-fbsvc-3c0e2df938.json:/app/config/firebase-service-account.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "--header=X-API-KEY: ${API_KEY:-your-secret-api-key-here}", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - upwork-job-listing-scraper-network

networks:
  upwork-job-listing-scraper-network:
    external: true
